{{ if .Values.generateSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ template "mariadb-fullname" . }}
  labels:
    app: {{ template "mariadb-fullname" . }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
{{ if .Values.keepSecret }}
  annotations:
    "helm.sh/resource-policy": keep
{{ end }}
type: Opaque
data:
  {{ if .Values.mysqlRootPassword }}
  mysql-root-password: {{ default "" .Values.mysqlRootPassword | b64enc | quote }}
  {{ else }}
  mysql-root-password: {{ randAlphaNum 16 | b64enc | quote }}
  {{ end }}
  {{ if .Values.mysqlPassword }}
  mysql-password: {{ default "" .Values.mysqlPassword | b64enc | quote }}
  {{ else }}
  mysql-password: {{ randAlphaNum 16 | b64enc | quote }}
  {{ end }}
{{ end }}