{{ if .Values.service.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ template "mariadb-galera.dnsname" . }}
  labels:
    app: {{ template "mariadb-fullname" . }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
  annotations:
    service.alpha.kubernetes.io/tolerate-unready-endpoints: "true"
spec:
  type: {{ default "ClusterIP" .Values.service.type }}
  clusterIP: {{ default "None" .Values.service.clusterIP }}
  ports:
  - name: mysql
{{ if .Values.service.nodePort }}
    nodePort: {{ .Values.service.nodePort }}
{{ end }}
    port: {{ default 3306 .Values.service.port }}
  selector:
    app: {{ template "mariadb-fullname" . }}
{{ end }}